apiVersion: v1
kind: Pod
metadata:
  name: pod-secret
spec:
  containers:
    - name: pod-secret
      image: registry.cn-hangzhou.aliyuncs.com/xuweizhi/demo:20220525230607
      ports:
        - containerPort: 8080
      volumeMounts:
        - name: db-secret
          mountPath: /db-secret
          readOnly: true
  volumes:
    - name: db-secret
      secret:
        secretName: db-pass


