apiVersion: v1
kind: Pod
metadata:
  name: pod-config
spec:
  containers:
    - name: pod-config
      image: registry.cn-hangzhou.aliyuncs.com/xuweizhi/demo:20220525230607
      #      command: ["/bin/bash","-c","java -jar /app.jar -D JAVA_OPTIONS=${LOG_LEVEL_CONFIG}"]
      ports:
        - containerPort: 8080
      volumeMounts:
        - name: config-volume
          mountPath: /root/config
          readOnly: true
        - name: pod-info
          mountPath: /etc/pod-info
      # env | grep LOG_LEVEL_CONFIG
      # echo ${LOG_LEVEL_CONFIG}
      env:
        # 参数在容器环境变量，可直接引用
        - name: LOG_LEVEL_CONFIG
          valueFrom:
            configMapKeyRef:
              name: config-test
              key: LOG_LEVEL
  volumes:
    - name: config-volume
      configMap:
        name: config-test
    - name: pod-info
      projected:
        sources:
          - downwardAPI:
              items:
                - path: "labels"
                  fieldRef:
                    fieldPath: metadata.labels
