apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: dubbo-consumer-demo
  name: dubbo-consumer-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dubbo-consumer-demo
  template:
    metadata:
      labels:
        app: dubbo-consumer-demo
    spec:
      # 与宿主机公用资源、端口
#      hostNetwork: true
      containers:
        - image: registry.cn-hangzhou.aliyuncs.com/xuweizhi/consumer
          name: dubbo-consumer-demo
          ports:
            - containerPort: 8000
            - containerPort: 20880
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: dubbo-provider-demo
  name: dubbo-provider-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dubbo-provider-demo
  template:
    metadata:
      labels:
        app: dubbo-provider-demo
    spec:
      # 与宿主机公用资源、端口
      #hostNetwork: true
      containers:
        - image: registry.cn-hangzhou.aliyuncs.com/xuweizhi/provider
          name: dubbo-provider-demo
          ports:
            - containerPort: 20880

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: dubbo-consumer-demo
  name: dubbo-consumer-demo  #修改service名称
spec:
  ports:
    - port: 8080
      targetPort: 8000
  selector:
    app: dubbo-consumer-demo
  type: ClusterIP

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: spring-boot
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  # 新增
  tls:
    - hosts:
        - demo.spring-boot.com
      secretName: tls-secret
  rules:
    - host: demo.spring-boot.com
      http:
        paths:
          - path: "/"
            pathType: Prefix
            backend:
              service:
                name: dubbo-consumer-demo
                port:
                  number: 8080
