apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: spring-boot
  name: spring-boot
spec:
  replicas: 2
  selector:
    matchLabels:
      app: spring-boot
#    matchExpressions:
#      # 选择标签
#      - { key: group, operator: In, value: [ dev, test ] }
  template:
    metadata:
      labels:
        group: dev
        app: spring-boot
    spec:
      containers:
        - image: registry.cn-hangzhou.aliyuncs.com/xuweizhi/demo:20220525230607
          name: spring-boot
          ports:
            - containerPort: 8080
          # 健康检查进程存活探针
          livenessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - ps -ef|grep java|grep -v grep
            initialDelaySeconds: 10
            periodSeconds: 10
            failureThreshold: 2
            successThreshold: 1
            timeoutSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: spring-boot
  name: spring-boot  #修改service名称
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: spring-boot
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: spring-boot
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  # 新增
  tls:
    - hosts:
        - demo.spring-boot.com
      secretName: tls-secret
  rules:
    - host: demo.spring-boot.com
      http:
        paths:
          - path: "/"
            pathType: Prefix
            backend:
              service:
                name: spring-boot
                port:
                  number: 8080
