apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{.name}}
  name: {{.name}}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{.name}}
  template:
    metadata:
      labels:
        app: {{.name}}
    spec:
      containers:
        - image: {{.image}}
          name: {{.name}}
          ports:
            - containerPort: {{.expose_port}}
#          resources:
#            # cup 与 memory 的区别：memory 和 cpu requests 不满足时无法启动
#            # 当资源不够时， cpu 会根据配置权重分配 cpu 核心数，memory 不足时停止容器
#            # cpu: 1024m 算一核，100m 0.1 核心
#            requests:
#              cpu: "100m"
#              memory: "200Mi"
#            # limits 申请不够时可以启动，requests 无法启动
#            limits:
#              cpu: "100m"
#              memory: "200Mi"
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{.name}}
  name: {{.name}}  #修改service名称
spec:
  ports:
    - port: 80
      targetPort: {{.expose_port}}
  selector:
    app: {{.name}}
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{.name}}
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  tls:
    - hosts:
        - {{.host}}
      secretName: tls-secret
  rules:
    - host: {{.host}}
      http:
        paths:
          - path: "/"
            pathType: Prefix
            backend:
              service:
                name: {{.name}}
                port:
                  number: 80
